### ISSUE TITLE
ModuleNotFoundError: No module named 'Middleware.llmapis.ollama_chat_api_image_specific_handler'

### ISSUE THREAD

**Issue by ymcki** [SomeOddCodeGuy/WilmerAI#22]
Does that mean a file called Middleware/llmapi/ollama_chat_api_image_specific_handler.py is missing?

```
$ python3 server.py 
Traceback (most recent call last):
  File "/tank/WilmerAI/server.py", line 6, in <module>
    from Middleware.core.open_ai_api import WilmerApi
  File "/tank/WilmerAI/Middleware/core/open_ai_api.py", line 18, in <module>
    from Middleware.workflows.categorization.prompt_categorizer import PromptCategorizer
  File "/tank/WilmerAI/Middleware/workflows/categorization/prompt_categorizer.py", line 5, in <module>
    from Middleware.workflows.managers.workflow_manager import WorkflowManager, logger
  File "/tank/WilmerAI/Middleware/workflows/managers/workflow_manager.py", line 10, in <module>
    from Middleware.services.llm_service import LlmHandlerService
  File "/tank/WilmerAI/Middleware/services/llm_service.py", line 3, in <module>
    from Middleware.llmapis.llm_api import LlmApiService
  File "/tank/WilmerAI/Middleware/llmapis/llm_api.py", line 15, in <module>
    from .ollama_chat_api_image_specific_handler import OllamaApiChatImageSpecificHandler
ModuleNotFoundError: No module named 'Middleware.llmapis.ollama_chat_api_image_specific_handler'
```

**Comment by SomeOddCodeGuy** [comment]
Are one of your endpoints of this type: "ollamaApiChatImageSpecific"? If so, swap it to "ollamaApiChat" for now.

**Comment by ymcki** [comment]
Fixed. Thanks
